version: '2'
services:
    nginx:
        image: nginx:1.10
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
            - ./wwwroot:/var/wwwroot:ro
        ports:
            - "80:80"
        links:
            - php-fpm
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile-php-fpm
        volumes:
            - ./wwwroot:/var/wwwroot
        links:
            - mysql
    mysql:
        #Enable not in MAC
        image: mysql:5.7
        #Enable in MAC
        # build:
            # context: .
            # dockerfile: Dockerfile-mysql-mac
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
